"""Add doctor nurse staff tables

Revision ID: b509161d5db6
Revises: d7e1a61a6788
Create Date: 2025-11-19 13:11:04.859887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b509161d5db6'
down_revision: Union[str, Sequence[str], None] = 'd7e1a61a6788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
