"""Create domain tables: doctor, nurse, staff, patient, token, specialty

Revision ID: d97e542fdc5b
Revises: 6d21f92f251c
Create Date: 2025-11-18 18:48:00.286594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd97e542fdc5b'
down_revision: Union[str, Sequence[str], None] = '6d21f92f251c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
